preloadImages([
    'R%20Business_archivos/SDLOGO.png',
    'R%20Business_archivos/images/bg-but2.gif',
    'R%20Business_archivos/images/bg-drop-li.gif',
    'R%20Business_archivos/images/bg-li-act.gif',
    'R%20Business_archivos/images/next-act.png',
    'R%20Business_archivos/images/prev-act.png',
    'R%20Business_archivos/images/slider-next-act.png',
    'R%20Business_archivos/images/slider-prev-act.png',
    'R%20Business_archivos/images/slider-stop-act.png'
]);